import { create } from 'zustand';
import type { ChatMessage } from '@curio/core';
import type { Envelope, WikiSummary } from '@curio/core';
import type { ToolEffect } from '../tools/types';

export type Role = 'user' | 'assistant';

/**
 * Which brain answers. 'ollama' is the local default; 'groq' is the cloud escape hatch
 * (any OpenAI-compatible endpoint, bring-your-own key). See CLAUDE.md — the owner relaxed the
 * "local only" rule so anyone can plug in whatever key they want.
 */
export type Brain = 'ollama' | 'groq';

/** Default cloud endpoint: Groq's OpenAI-compatible base (fast free tier). Any OpenAI-compatible
 *  endpoint works — the user can change it (presets or a custom URL) in the settings menu. */
export const DEFAULT_CLOUD_BASE_URL = 'https://api.groq.com/openai/v1';

/** A fast, current Groq default (`llama-3.3-70b-versatile`/`llama-3.1-8b-instant` were deprecated
 *  on 2026-06-17). Groq's lineup changes often — check console.groq.com/docs/models. Overridable. */
export const DEFAULT_GROQ_MODEL = 'openai/gpt-oss-20b';

/**
 * Models to fall back to when the primary Groq model fails (typically a 429: its daily token
 * quota is spent). Each Groq model has its OWN per-day limit, and the lighter instant model has
 * a far higher one — so when the 70B is exhausted, the 8B still answers. Overridable with
 * VITE_GROQ_FALLBACK_MODELS (comma-separated) in .env.local.
 */
export const DEFAULT_GROQ_FALLBACKS = ['llama-3.1-8b-instant'];

/** The two reading surfaces: the chat, or a pasted article. Both use the same engine. */
export type Mode = 'chat' | 'read';

/** A pasted article being read. `id` changes each paste so its lookups never collide. */
export interface Article {
  id: string;
  content: string;
}

export interface Message {
  id: string;
  role: Role;
  content: string;
  /** True while assistant tokens are still streaming in. */
  streaming?: boolean;
  /** Set if generating this reply failed. */
  error?: string;
  /** True when `content` is OpenUI Lang (a composed-components reply), not markdown text. */
  generative?: boolean;
  /** Visual effects produced by tool modules during the reply (e.g. an Excalidraw diagram). */
  effects?: ToolEffect[];
}

/** A cached / in-flight term description, keyed by `${messageId} ${term}`. */
export interface DescriptionEntry {
  status: 'loading' | 'done' | 'error';
  text: string;
  error?: string;
}

/**
 * Cache key for a lookup. Includes the active model so switching models never serves a
 * description generated by a different one; includes the messageId so the same word in two
 * messages (or two pasted articles — each gets a fresh id) never collides.
 */
export function descriptionKey(model: string, messageId: string, term: string): string {
  return `${model} ${messageId} ${term.trim().toLowerCase()}`;
}

/** A cached / in-flight generative-UI result for the modal, keyed like descriptions. */
export interface GenerativeEntry {
  status: 'loading' | 'done' | 'error';
  /** The validated component envelope, once generation succeeds. */
  envelope?: Envelope;
  /** The fuller explanation shown in the modal — the actual "more" behind "See more". */
  deep?: string;
  /** Wikipedia card (photo + facts + link) when the term has an article; null if none. */
  wiki?: WikiSummary | null;
  /** Short related concepts to explore next — clickable links in the modal. */
  related?: string[];
  /** Contextualizer: why this term appears in THIS text, what depends on it. */
  whyHere?: string;
  /** Connector: which other terms in the text relate to this one, and how. */
  connections?: string;
  error?: string;
}

/**
 * The word or phrase whose description is open. Anchored to the LIVE DOM (an element
 * for a word, a Range for a phrase) so the popover follows the text on scroll.
 */
export interface Selection {
  messageId: string;
  text: string;
  /** Surrounding text (the block/paragraph) sent to the model as context. */
  context: string;
  /** The clicked word element — anchored to and highlighted while open (word click). */
  el: HTMLElement | null;
  /** The selected range (phrase select). */
  range: Range | null;
  /** Nearest block element, so Floating UI can track scroll for a range. */
  block: HTMLElement | null;
}

interface ChatState {
  messages: Message[];
  /** Which reading surface is active: the chat or a pasted article. */
  mode: Mode;
  /** The article being read in `read` mode, or null before one is pasted. */
  article: Article | null;
  /** Which brain answers: local Ollama or a cloud (OpenAI-compatible) endpoint. Persisted. */
  brain: Brain;
  /** Base URL of the cloud endpoint, e.g. Groq / OpenRouter / LocalAI / your own. Persisted. */
  cloudBaseUrl: string;
  /** Bring-your-own API key for the cloud endpoint. Persisted to localStorage only. */
  groqApiKey: string;
  /** Cloud model id, e.g. 'llama-3.3-70b-versatile'. Persisted. */
  groqModel: string;
  /** Active Ollama model tag for chat replies, or null until one is chosen. */
  model: string | null;
  /** Model tag used by the (separate, fast) describer; falls back to `model`. */
  describeModel: string | null;
  /**
   * Gen UI mode (global): when true, the assistant's chat replies AND the article reader
   * COMPOSE components (OpenUI) instead of plain text. One switch for every surface. Persisted.
   */
  genUI: boolean;
  /** The word/phrase whose description popover is open, or null. */
  selection: Selection | null;
  /** True when the description has been expanded from the small popover into the modal. */
  expanded: boolean;
  /** Description cache + in-flight state, keyed by descriptionKey(). */
  descriptions: Record<string, DescriptionEntry>;
  /** Generative-UI (modal) cache + in-flight state, keyed by descriptionKey(). */
  generatives: Record<string, GenerativeEntry>;

  setModel: (model: string | null) => void;
  setDescribeModel: (model: string | null) => void;
  setBrain: (brain: Brain) => void;
  setCloudBaseUrl: (url: string) => void;
  setGroqApiKey: (key: string) => void;
  setGroqModel: (model: string) => void;
  setGenUI: (on: boolean) => void;

  /** Switch reading surface (closes any open description). */
  setMode: (mode: Mode) => void;
  /** Set (or clear, with null) the article being read; a new paste gets a fresh id. */
  setArticle: (content: string | null) => void;

  addUserMessage: (content: string) => void;
  /** Create an empty assistant message and return its id, for streaming into. */
  startAssistantMessage: (generative?: boolean) => string;
  appendToMessage: (id: string, delta: string) => void;
  finishMessage: (id: string) => void;
  failMessage: (id: string, error: string) => void;
  /** Attach visual tool effects (Excalidraw diagrams, ...) to an assistant message. */
  setMessageEffects: (id: string, effects: ToolEffect[]) => void;

  setSelection: (selection: Selection | null) => void;
  /** Grow the popover into the modal, or shrink it back to the popover. */
  setExpanded: (expanded: boolean) => void;

  setDescription: (key: string, entry: DescriptionEntry) => void;
  /** Drop a cached description (used when an in-flight lookup is cancelled). */
  clearDescription: (key: string) => void;
  setGenerative: (key: string, entry: GenerativeEntry) => void;
  /** Drop a cached generative result (used when an in-flight generation is cancelled). */
  clearGenerative: (key: string) => void;
}

function newId(): string {
  return crypto.randomUUID();
}

/** Keys for the handful of brain settings we persist across reloads. */
const LS = {
  brain: 'curio.brain',
  cloudBaseUrl: 'curio.cloudBaseUrl',
  groqKey: 'curio.groqApiKey',
  groqModel: 'curio.groqModel',
  genUI: 'curio.genUI',
};

function lsGet(key: string): string | null {
  try {
    return localStorage.getItem(key);
  } catch {
    return null;
  }
}

function lsSet(key: string, value: string): void {
  try {
    localStorage.setItem(key, value);
  } catch {
    // Private mode / quota — settings just won't persist; not worth surfacing.
  }
}

// Initial brain settings: a value set in `.env.local` (VITE_*) WINS, so you can configure the
// key/model/brain in files and never touch the header. If unset, fall back to what the UI last
// saved (localStorage), then to defaults.
const ENV = import.meta.env;
// GROQ API keys — comma-separated for rotation on rate limit.
const initialGroqKey = ENV.VITE_GROQ_API_KEY?.trim() || (lsGet(LS.groqKey) ?? '');
const initialGroqModel = ENV.VITE_GROQ_MODEL?.trim() || lsGet(LS.groqModel) || DEFAULT_GROQ_MODEL;
const initialCloudBaseUrl =
  ENV.VITE_CLOUD_BASE_URL?.trim() || lsGet(LS.cloudBaseUrl) || DEFAULT_CLOUD_BASE_URL;

const envFallbacks = ENV.VITE_GROQ_FALLBACK_MODELS?.split(',')
  .map((m) => m.trim())
  .filter(Boolean);
const groqFallbacks = envFallbacks?.length ? envFallbacks : DEFAULT_GROQ_FALLBACKS;

/**
 * The ordered list of Groq models to try for a single request: the chosen primary first, then
 * the fallbacks. Deduped (so if you pick the 8B as primary it isn't tried twice) and never empty.
 */
export function groqModelChain(primary: string): string[] {
  const chain = [primary, ...groqFallbacks].map((m) => m.trim()).filter(Boolean);
  return [...new Set(chain)];
}
// If a key is provided in the env, default to Groq unless explicitly told otherwise.
const initialBrain: Brain =
  ENV.VITE_BRAIN === 'groq' || (ENV.VITE_BRAIN !== 'ollama' && ENV.VITE_GROQ_API_KEY?.trim())
    ? 'groq'
    : lsGet(LS.brain) === 'groq'
      ? 'groq'
      : 'ollama';

export const useChatStore = create<ChatState>((set) => ({
  messages: [],
  mode: 'chat',
  article: null,
  brain: initialBrain,
  cloudBaseUrl: initialCloudBaseUrl,
  groqApiKey: initialGroqKey,
  groqModel: initialGroqModel,
  model: null,
  describeModel: null,
  genUI: lsGet(LS.genUI) === '1',
  selection: null,
  expanded: false,
  descriptions: {},
  generatives: {},

  setModel: (model) => set({ model }),
  setDescribeModel: (describeModel) => set({ describeModel }),
  setBrain: (brain) => {
    lsSet(LS.brain, brain);
    set({ brain });
  },
  setCloudBaseUrl: (cloudBaseUrl) => {
    lsSet(LS.cloudBaseUrl, cloudBaseUrl);
    set({ cloudBaseUrl });
  },
  setGroqApiKey: (groqApiKey) => {
    lsSet(LS.groqKey, groqApiKey);
    set({ groqApiKey });
  },
  setGroqModel: (groqModel) => {
    lsSet(LS.groqModel, groqModel);
    set({ groqModel });
  },
  setGenUI: (genUI) => {
    lsSet(LS.genUI, genUI ? '1' : '0');
    set({ genUI });
  },

  // Switching surface always closes any open description.
  setMode: (mode) => set({ mode, selection: null, expanded: false }),
  setArticle: (content) =>
    set({
      article: content ? { id: newId(), content } : null,
      selection: null,
      expanded: false,
    }),

  addUserMessage: (content) =>
    set((s) => ({ messages: [...s.messages, { id: newId(), role: 'user', content }] })),

  startAssistantMessage: (generative = false) => {
    const id = newId();
    set((s) => ({
      messages: [...s.messages, { id, role: 'assistant', content: '', streaming: true, generative }],
    }));
    return id;
  },

  appendToMessage: (id, delta) =>
    set((s) => ({
      messages: s.messages.map((m) => (m.id === id ? { ...m, content: m.content + delta } : m)),
    })),

  finishMessage: (id) =>
    set((s) => ({
      messages: s.messages.map((m) => (m.id === id ? { ...m, streaming: false } : m)),
    })),

  failMessage: (id, error) =>
    set((s) => ({
      messages: s.messages.map((m) => (m.id === id ? { ...m, streaming: false, error } : m)),
    })),

  setMessageEffects: (id, effects) =>
    set((s) => ({
      messages: s.messages.map((m) => (m.id === id ? { ...m, effects } : m)),
    })),

  // A new (or cleared) selection always starts collapsed — the modal never survives
  // a change of the described word.
  setSelection: (selection) => set({ selection, expanded: false }),
  setExpanded: (expanded) => set({ expanded }),

  setDescription: (key, entry) =>
    set((s) => ({ descriptions: { ...s.descriptions, [key]: entry } })),

  clearDescription: (key) =>
    set((s) => {
      if (!(key in s.descriptions)) return s;
      const next = { ...s.descriptions };
      delete next[key];
      return { descriptions: next };
    }),

  setGenerative: (key, entry) => set((s) => ({ generatives: { ...s.generatives, [key]: entry } })),

  clearGenerative: (key) =>
    set((s) => {
      if (!(key in s.generatives)) return s;
      const next = { ...s.generatives };
      delete next[key];
      return { generatives: next };
    }),
}));

/** Build the message list to send to Ollama for the chat completion. */
export function toChatMessages(messages: Message[], systemPrompt: string): ChatMessage[] {
  return [
    { role: 'system', content: systemPrompt },
    ...messages.filter((m) => !m.error).map((m) => ({ role: m.role, content: m.content })),
  ];
}
