import { createBrain, FallbackProvider, type LlmProvider } from '@curio/core';
import { groqModelChain, useChatStore } from '../app/store';

/**
 * The web app reaches Groq through a same-origin proxy (`/groq` → api.groq.com/openai/v1,
 * see vite.config.ts) so there is no CORS and no user setup — the same trick as `/ollama`.
 */
const GROQ_PROXY_BASE = '/groq';

/** The two lookup roles: chat replies vs. the (smaller, faster) word describer. */
export type BrainRole = 'chat' | 'describe';

export interface ActiveBrain {
  provider: LlmProvider;
  /**
   * Identity for the description cache key — distinct per brain+model, so switching brains or
   * models never serves an answer generated by a different one.
   */
  modelId: string;
  /** Whether the brain can actually run (has a model / key). */
  ready: boolean;
  /** Short user-facing reason when not ready. */
  reason?: string;
}

/**
 * Resolve the currently-selected brain into a live provider + a cache identity. Reads the store
 * imperatively, so call it inside effects at fire time. For reactive cache keys / effect deps,
 * use {@link useActiveModelId}, which subscribes to the relevant slices.
 */
export function getBrain(role: BrainRole): ActiveBrain {
  const s = useChatStore.getState();

  if (s.brain === 'groq') {
    const model = s.groqModel.trim();
    const apiKey = s.groqApiKey.trim();
    // Try the chosen model first, then lighter fallbacks — so a spent daily quota (429) on the
    // 70B silently drops to the 8B instead of erroring. One model → no wrapper, same as before.
    const chain = groqModelChain(model);
    const providers = chain.map((m) =>
      createBrain({ kind: 'openai', name: 'groq', model: m, apiKey, baseUrl: GROQ_PROXY_BASE }),
    );
    return {
      provider: providers.length > 1 ? new FallbackProvider(providers) : providers[0],
      modelId: `groq:${model}`,
      ready: !!model && !!apiKey,
      reason: !apiKey
        ? 'Falta la API key de Groq: ponla en apps/web/.env.local (VITE_GROQ_API_KEY).'
        : !model
          ? 'Falta el modelo de Groq (VITE_GROQ_MODEL).'
          : undefined,
    };
  }

  // Ollama: chat prefers the larger model, the describer the small fast one.
  const model = (role === 'describe' ? (s.describeModel ?? s.model) : s.model) ?? '';
  return {
    provider: createBrain({ kind: 'ollama', model, keepAlive: '10m' }),
    modelId: model,
    ready: !!model,
    reason: !model ? 'No model available. Pull one with `ollama pull llama3.2:3b`.' : undefined,
  };
}

/** Reactive cache identity for `role`, tracking brain + model changes. Use in components/hooks. */
export function useActiveModelId(role: BrainRole): string {
  return useChatStore((s) => {
    if (s.brain === 'groq') return `groq:${s.groqModel.trim()}`;
    return ((role === 'describe' ? (s.describeModel ?? s.model) : s.model) ?? '') as string;
  });
}
