import { createBrain, type LlmProvider } from '@curio/core';
import { useChatStore } from '../app/store';

/**
 * The cloud brain reaches ANY OpenAI-compatible endpoint through a same-origin dynamic proxy
 * (`/llm`, see vite.config.ts): the browser POSTs to `/llm/chat/completions` with the real base URL
 * in `x-llm-base-url`, and the dev server forwards it — no CORS, works with Groq / OpenRouter /
 * LocalAI / your own server. The user's key rides in the Authorization header as usual.
 */
const LLM_PROXY_BASE = '/llm';

/** The two lookup roles: chat replies vs. the (smaller, faster) word describer. */
export type BrainRole = 'chat' | 'describe';

export interface ActiveBrain {
  provider: LlmProvider;
  /**
   * Identity for the description cache key — distinct per brain+model, so switching brains or
   * models never serves an answer generated by a different one.
   */
  modelId: string;
  /** Whether the brain can actually run (has a model / key). */
  ready: boolean;
  /** Short user-facing reason when not ready. */
  reason?: string;
}

/**
 * Resolve the currently-selected brain into a live provider + a cache identity. Reads the store
 * imperatively, so call it inside effects at fire time. For reactive cache keys / effect deps,
 * use {@link useActiveModelId}, which subscribes to the relevant slices.
 */
export function getBrain(role: BrainRole): ActiveBrain {
  const s = useChatStore.getState();

  if (s.brain === 'groq') {
    const model = s.groqModel.trim();
    const apiKey = s.groqApiKey.trim();
    const base = s.cloudBaseUrl.trim().replace(/\/$/, '');
    // Any OpenAI-compatible endpoint, reached through the dynamic /llm proxy (the real URL travels
    // in x-llm-base-url). The key is OPTIONAL — a local endpoint (LM Studio / LocalAI) needs none;
    // if one IS required, the request 401s with a clear message.
    return {
      provider: createBrain({
        kind: 'openai',
        name: 'cloud',
        model,
        apiKey,
        baseUrl: LLM_PROXY_BASE,
        headers: { 'x-llm-base-url': base },
      }),
      modelId: `cloud:${base}:${model}`,
      ready: !!base && !!model,
      reason: !base
        ? 'No endpoint URL. Set VITE_CLOUD_BASE_URL in apps/web/.env.local.'
        : !model
          ? 'No model id. Set VITE_GROQ_MODEL in apps/web/.env.local.'
          : undefined,
    };
  }

  // Ollama: chat prefers the larger model, the describer the small fast one.
  const model = (role === 'describe' ? (s.describeModel ?? s.model) : s.model) ?? '';
  // Brain-agnostic reason: a local model OR an API endpoint both count as "a model", so the
  // message never assumes Ollama.
  const noModel =
    s.locale === 'es'
      ? 'No hay ningún modelo disponible. Añade un modelo local o configura un endpoint de API.'
      : 'No model available. Add a local model or configure an API endpoint.';
  return {
    provider: createBrain({ kind: 'ollama', model, keepAlive: '10m' }),
    modelId: model,
    ready: !!model,
    reason: !model ? noModel : undefined,
  };
}

/** Reactive cache identity for `role`, tracking brain + model changes. Use in components/hooks. */
export function useActiveModelId(role: BrainRole): string {
  return useChatStore((s) => {
    if (s.brain === 'groq') return `cloud:${s.cloudBaseUrl.trim()}:${s.groqModel.trim()}`;
    return ((role === 'describe' ? (s.describeModel ?? s.model) : s.model) ?? '') as string;
  });
}
